# default admin account
def_admin_user: "admin"
def_admin_pass: "klnm12"
def_admin_email: "admin@musashi.com"

user_mem: "mem"
user_pa: "pa"
user_admin: "admin"
user_emailusername: "qa_musashi"
user_emaildomain: "@musashi.ph"
user_password: "12345678"
user_project: "proj"

res_instance: "inst"
res_snapshot: "instsnap"
res_secgroup: "secgroup"
res_keypair: "keypair"
res_volume: "vol"

common_description: "test"

keypair_name: "keypair"
keypair_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCodIikZrqutsBFB0LTREE7uLhGQpdRga7NYcv3dhVk/Pd5VNV5zG+1zHuR/YbphFnVD30gmQH99HLYJ/8xIHDBBYkYc1GxbuwWhm67sObYYAC2nLBbVCNygoem++mqkgqcp0tqQbgOyL5k1H6TTN8F0nqSFv1dcOvm6XgBWJ9cw6qLPLrLv2I5nejCYLYSAFmZYAu/Hsb9sJ9phdVjPD8yKdynK2wkbRXckzOS6LQPZzAIzlyousnA3CJLfLfiGuJrIrXMvP+LW7iHPW1u9hlvgmdhZLqJQlW7e5baLM+9WIVnpQS+CvucFVEH0EUvlqZB8fmmXVCoCkjnfoJd0Iyl carolinejandayan@Carolines-Mac.local"